heat_template_version: 2016-04-08

description: >
  OpenStack Congress service configured with Puppet

parameters:
  CongressPassword:
    description: The password for the congress service account.
    type: string
    hidden: true
  Debug:
    type: string
    default: ''
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number

outputs:
  role_data:
    description: Role data for the Congress role.
    value:
      config_settings:
        tripleo::haproxy::congress: true

        congress_password: {get_param: CongressPassword}
        congress::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://congress:'
              - {get_param: CongressPassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/congress'
        congress::admin_tenant_name: 'service'    
        congress::keystone_password: {get_param: CtongressPassword}
        congress::auth_uri: {get_param: keystone_auth_uri}
        congress::admin_user: congress
        congress::identity_uri: {get_param: keystone_identity_uri}
        congress::debug: {get_param: Debug}
        congress::rpc_backend: rabbit
        congress::rabbit_userid: {get_param: RabbitUserName}
        congress::rabbit_password: {get_param: RabbitPassword}
        congress::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        congress::rabbit_port: {get_param: RabbitClientPort}

        congress::db::mysql::password: {get_param: CongressPassword}
        congress::db::mysql::user: congress
        congress::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
        congress::db::mysql::dbname: congress
        congress::db::mysql::allowed_hosts:
          - '%'
          - "%{hiera('mysql_bind_host')}"


      step_config: |
        include ::tripleo::profile::base::congress
